name: 'Smart Deploy Kubernetes Action'
description: 'Deploy changes via helm, update DNS'
author: "InfraWay"

inputs:
  action:
    description: 'Action to do rollout|delete'
    required: true
  namespace:
    description: 'Kubernetes namespace'
    required: true
  release:
    description: 'Helm release'
    required: true
  chart:
    description: 'Helm chart'
    required: true
  host:
    description: 'Host of deployment'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.namespace }}
    - ${{ inputs.release }}
    - ${{ inputs.chart }}
    - ${{ inputs.host }}

branding:
  icon: "anchor"
  color: "blue"
