# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'

      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go mod download

      # Run build of the application
      - name: Run build
        run: go build .

      # Run vet & lint on the code
      - name: Run vet & lint
        run: |
          go vet .
          golint .

      - name: Publish Docker image
        run: |
          export TAG=${GITHUB_SHA:0:7}
          export REGISTRY_IMAGE="docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | awk '{print tolower($0)}')/web"
          docker build -t $REGISTRY_IMAGE:$TAG .
          docker push $REGISTRY_IMAGE:$TAG

#      # Run testing on the code
#      - name: Run testing
#        run: cd test && go test -v